### PR TITLE
fix cursor is null

### PR DESCRIPTION
**Pull request by windless**

### CODE REVIEW

**Comment by piyushcoader** [comment]
@aayushcoder

**Comment by piyushcoader** [comment]
do we need this i mean what might be the use case where cursor is null , one might be removing all  call logs

**Comment by windless** [comment]
I don't know the what's use case too, but i receive a crash exception about the cursor:

```
java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndex(java.lang.String)' on a null object reference
    at com.wscodelabs.callLogs.CallLogModule.show(CallLogModule.java)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.facebook.react.cxxbridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java)
    at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java)
    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java)
    at android.os.Looper.loop(Looper.java:224)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by piyushcoader** [comment]
:+1:

**Pull request merged**
